name: Python Telegram Bot CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.8, 3.9, 3.10]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyTelegramBotAPI beautifulsoup4 requests-tor

      - name: Lint code with flake8
        run: |
          pip install flake8
          flake8 .

      # Если у вас есть тесты, можно добавить шаг запуска тестов
      #- name: Run tests
      #  run: |
      #    pip install -r requirements.txt
      #    pytest
